
version: 2.1
kind: pipeline
type: docker
name: jenkins

jobs:
  mamada2:
    docker:
      - image: brenom2k/brenolatest:late
    environment:
        aws_access_key_id: AWS_ACCESS_KEY_ID
        aws_secret_access_key: AWS_SECRET_ACCESS_KEY
        aws_default_region: AWS_DEFAULT_REGION

        
    
    steps:
      - add_ssh_keys:
          fingerprints:
           - "90:23:49:7c:b1:52:7a:e4:ed:ef:d0:98:e8:c8:ee:b7"
      
      - checkout
      - run: 
         name: "Git install"
         command: "apt install git -y" 

#      - run: 
#         name: "Ansible installing"
#         command: "apt install ansible -y"
      
#      - run:
#         name: "Ansible installing package aws"
#         command: "ansible-galaxy collection install amazon.aws"   
      
      - run:
          name: "Terraform init"
          command: "terraform init"
      
      - run: 
          name: "Spin up EC2"
          command: "terraform destroy -auto-approve"
      
#      - run:
#          name: "Python3 && Boto"
#          command: "apt install python3 -y && apt install python3-pip && pip install boto3"

#      - run:
#         name: "Ansible list inventory"   
#         command: "ansible-inventory -i inventory.aws_ec2.yml --graph" 
      
#      - run:
#          name: "Ansible ping"
#          command: ansible -vvvv -i inventory.aws_ec2.yml tag_name_Jenkins -u ubuntu --ssh-common-args='-o StrictHostKeyChecking=no' site.yml

#      - run: 
#         name: "Playbook apply"
#         command: |
#          ls
#          ansible-playbook -i inventory.aws_ec2.yml --limit "tag_name_Jenkins" -u ubuntu --ssh-common-args='-o StrictHostKeyChecking=no' site.yml

workflows:
  say-hello-workflow:
    jobs:
      - mamada2
