
version: 2.1
kind: pipeline

jobs:
  mamada2:
    docker:
      - image: brenom2k/brenolatest:late
    environment:
        aws_access_key_id: AWS_ACCESS_KEY_ID
        aws_secret_access_key: AWS_SECRET_ACCESS_KEY
        aws_default_region: AWS_DEFAULT_REGION 
    
    steps:
      - checkout
      - run: 
         name: "Git install"
         command: "apt install git" 


      - run:
          name: "Terraform init"
          command: "terraform init"
      

      - run: 
          name: "Spin up EC2"
          command: "terraform apply  -auto-approve"

workflows:
  say-hello-workflow:
    jobs:
      - mamada2
